print("========================================")
print("           MY PYTHON PROFILE") 
print("========================================")
print()
print("Name      : Mahfoz")
print("Goal      : Become a Professional Coder")
print("Language  : Python")
print("Level     : Beginner")
print("Learning  : Python Programming")
print()
print("----------------------------------------")
print("        I AM STARTING MY JOURNEY!")
print("----------------------------------------")
print()
print("========================================")