print("+------------------------------------+")
print("|           PYTHON JOURNEY           |")
print("+------------------------------------+")
print("|                                    |")
print("|  Day     : 01                      |")
print("|  Topic   : 05 Task                 |")
print("|  Level   : Beginner                |")
print("|                                    |")
print("+------------------------------------+")
print("|                                    |")
print("         KEEP CODING-MAHFOZ...!       ")
print("+------------------------------------+")